cmake: Use check_symbol_exists for checking for sin() in -lm
This avoids misdetections if -Werror is included in CMAKE_C_FLAGS.

Previously, with -Werror, the "check_library_exists(m sin "" HAVE_LIBM)"
or "check_function_exists(sin HAVE_DEFAULT_MATH)" failed due to warnings
like this:

    <command-line>: error: conflicting types for built-in function ‘sin’; expected ‘double(double)’ [-Werror=builtin-declaration-mismatch]
    CMakeFiles/CMakeScratch/TryCompile-g2Wj9s/CheckFunctionExists.c:7:3: note: in expansion of macro ‘CHECK_FUNCTION_EXISTS’
        7 |   CHECK_FUNCTION_EXISTS(void);
          |   ^~~~~~~~~~~~~~~~~~~~~
    CMakeFiles/CMakeScratch/TryCompile-g2Wj9s/CheckFunctionExists.c:1:1: note: ‘sin’ is declared in header ‘<math.h>’
      +++ |+#include <math.h>
        1 | #ifdef CHECK_FUNCTION_EXISTS
    cc1: all warnings being treated as errors
    ninja: build stopped: subcommand failed.